import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";
import SessionProvider from "@/hocs/session-provider";
import { authOptions } from "@/lib/auth";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("rootlayout");

  return (
    <html lang="en">
      <body className={"m-10"}>
        <SessionProvider>{children}</SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
